language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

matrix:
    fast_finish: true

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - travis_retry composer self-update

install:
    - travis_retry composer update --no-interaction --prefer-dist $COMPOSER_OPTS

script:
    - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
